################################################################################
#
# This file is part of the package nix-hs. It is subject to the license
# terms in the LICENSE file found in the top-level directory of this
# distribution and at:
#
#   git://git.devalot.com/nix-hs.git
#
# No part of this package, including this file, may be copied, modified,
# propagated, or distributed except according to the terms contained in
# the LICENSE file.

################################################################################
{ stdenv, pkgs, lib, ...}:

################################################################################
fn: # This is the function/file generated by cabal2nix.

{ src                            # Where to get the package from.
, haskell ? pkgs.haskellPackages # Pass this in from your Haskell overrides.
, buildInputs ? []               # Extra packages needed during building.
, postInstall ? ""               # Extra install steps
, builderOptions ? { }           # Extra options to pass to the Haskell mkDerivation
}:

################################################################################
let callPackage = haskell.callPackage fn {
      mkDerivation = { buildTools ? []
                     , ...
                     }@args:
      haskell.mkDerivation (args // builderOptions // {
        buildTools  = buildInputs ++ buildTools;
        postInstall = postInstall;
        src         = src;
      });
    };

in callPackage
