name: tests
on: pull_request
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: [ghc8104]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
    - uses: cachix/cachix-action@v10
      with:
        name: nix-hs
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: test/test.sh '${{ matrix.ghc }}'
